language: python

python:
    - "2.6"
    - "2.7"

env:
    - DJANGO=1.4.13
    - DJANGO=1.5.8

install:
    - pip install -q coveralls Django==$DJANGO --use-mirrors
    - pip install -r requirements.txt

services:
    - memcache

script:
    - coverage run test_suite.py

after_success:
    - coveralls
